[pressure]
sea_pressure = 10013.25

[height]
high = 35
low = 10
continue_number = 11

[PID]
P = 0.004
I = 0.03
D = 0.0004

[pin]
Rmotor = 12
Lmotor = 13

[camera]
start_distance = 0.003
Angle_of_View = 54

[gps]
goal_lat = 0
goal_long = 0

[icm_calib]
learning_rate = 0.0001

[state]
state = 0
